version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies
      - npm install --unsafe-perm=true
      - chmod +x node_modules/.bin/react-scripts

  build:
    commands:
      - echo Building React app
      - npm run build

  post_build:
    commands:
      - echo Uploading build to S3
      - if [ -d build ]; then aws s3 sync build/ s3://employeeinfo-stack-reactfrontendbucket-2yz6cirkkmcr --delete; else echo "Build folder not found"; exit 1; fi

artifacts:
  files:
    - '**/*'
